# ---------------------------------------------------------
# --
# ---------------------------------------------------------

server:
  port: 8082

spring:
  application:
    name: Inditex - PoT

  # Database configuration params for H2
  datasource:
    url: jdbc:h2:mem:inditexdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


